// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using MolasLubes.Infrastructure.Persistence;

#nullable disable

namespace MolasLubes.Infrastructure.Persistence.Migrations.Live2021Cache
{
    [DbContext(typeof(Live2021CacheDbContext))]
    partial class Live2021CacheDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MolasLubes.Domain.Entities.Cache.CacheGermaxProduct", b =>
                {
                    b.Property<string>("ItemCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ItemGroupName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EngineCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GermaxArticleNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OemPartNumber")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PartsCatalog")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FitForAuto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AllImageUrls")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MatchMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("MatchScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("ScrapedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastSapSeedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasDefaultValue(true)
                        .HasColumnType("bit");

                    b.Property<string>("ScrapeStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ScrapeError")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("ItemCode");

                    b.HasIndex("GermaxArticleNumber")
                        .HasDatabaseName("IX_CacheGermaxProducts_GermaxArticleNumber");

                    b.HasIndex("ItemGroupName")
                        .HasDatabaseName("IX_CacheGermaxProducts_ItemGroupName");

                    b.HasIndex("EngineCode")
                        .HasDatabaseName("IX_CacheGermaxProducts_EngineCode");

                    b.HasIndex("ScrapedAt")
                        .HasDatabaseName("IX_CacheGermaxProducts_ScrapedAt");

                    b.ToTable("CacheGermaxProducts", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
