// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MolasLubes.Infrastructure.Persistence;

#nullable disable

namespace MolasLubes.Infrastructure.Migrations
{
    [DbContext(typeof(MolasCacheDbContext))]
    [Migration("20260309140000_AddSalesOrderDetails")]
    partial class AddSalesOrderDetails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MolasLubes.Domain.Entities.Cache.CacheCustomer", b =>
                {
                    b.Property<string>("CardCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("AvailableCredit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CreditLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CreditUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastSapDeltaAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OdooCustomerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OdooErrorMsg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OdooLastSync")
                        .HasColumnType("datetime2");

                    b.Property<string>("OdooPartnerId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OdooStatus")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("OdooSyncDir")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("OutstandingBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PriceList")
                        .HasColumnType("int");

                    b.Property<int?>("SlpCode")
                        .HasColumnType("int");

                    b.HasKey("CardCode");

                    b.HasIndex("OdooPartnerId");

                    b.HasIndex("OdooStatus");

                    b.HasIndex("PriceList");

                    b.HasIndex("SlpCode");

                    b.ToTable("CacheCustomers", (string)null);
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Cache.CacheDelivery", b =>
                {
                    b.Property<int>("SapDocEntry")
                        .HasColumnType("int");

                    b.Property<int?>("BaseOrderEntry")
                        .HasColumnType("int");

                    b.Property<string>("CardCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("DeliveredQty")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSapSyncAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OdooDeliveryId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OdooErrorMsg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OdooLastSync")
                        .HasColumnType("datetime2");

                    b.Property<string>("OdooStatus")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("OdooSyncDir")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("SapDocNum")
                        .HasColumnType("int");

                    b.Property<DateTime>("SapUpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("SapDocEntry");

                    b.HasIndex("DeliveryDate");

                    b.HasIndex("LastSapSyncAt");

                    b.HasIndex("OdooDeliveryId");

                    b.ToTable("CacheDeliveries", (string)null);
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Cache.CacheDeliveryLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseEntry")
                        .HasColumnType("int");

                    b.Property<int>("BaseLine")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("GrossBuyPr")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("LineNum")
                        .HasColumnType("int");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OdooErrorMsg")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("OdooLastSync")
                        .HasColumnType("datetime2");

                    b.Property<string>("OdooMoveId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OdooSalesOrderLineId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OdooStatus")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("OdooSyncDir")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("SapDocEntry")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OdooMoveId");

                    b.HasIndex("SapDocEntry");

                    b.ToTable("CacheDeliveryLines", (string)null);
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Cache.CacheInvoice", b =>
                {
                    b.Property<int>("SapDocEntry")
                        .HasColumnType("int");

                    b.Property<int>("BaseOrderEntry")
                        .HasColumnType("int");

                    b.Property<DateTime>("CachedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CardCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CardName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DocDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DocTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OdooErrorMsg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OdooInvoiceId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("OdooLastSync")
                        .HasColumnType("datetime2");

                    b.Property<string>("OdooStatus")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("OdooSyncDir")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("SapDocNum")
                        .HasColumnType("int");

                    b.Property<decimal>("VatSum")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SapDocEntry");

                    b.HasIndex("OdooInvoiceId");

                    b.HasIndex("OdooStatus");

                    b.ToTable("CacheInvoices", (string)null);
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Cache.CacheInvoiceLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseEntry")
                        .HasColumnType("int");

                    b.Property<int>("BaseLine")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("GrossBuyPr")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OdooErrorMsg")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OdooInvoiceLineId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("OdooLastSync")
                        .HasColumnType("datetime2");

                    b.Property<string>("OdooStatus")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("OdooSyncDir")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("SapDocEntry")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OdooInvoiceLineId");

                    b.HasIndex("SapDocEntry");

                    b.ToTable("CacheInvoiceLines", (string)null);
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Cache.CacheLiquiMolyProduct", b =>
                {
                    b.Property<string>("ArticleNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("AllImageUrls")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AllPackagingSizes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Approvals")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackagingSize")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal?>("Liter")
                        .HasColumnType("decimal(8,3)");

                    b.Property<string>("ProductInfoPdfUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProductUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SafetyDataSheetPdfUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ScrapedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Specifications")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecGrade")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SubCategory")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ArticleNumber");

                    b.HasIndex("Category");

                    b.HasIndex("IsActive");

                    b.HasIndex("ScrapedAt");

                    b.ToTable("CacheLiquiMolyProducts", (string)null);
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Cache.CachePayment", b =>
                {
                    b.Property<int>("SapDocEntry")
                        .HasColumnType("int");

                    b.Property<DateTime>("CachedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CardCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("DocDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InvoiceDocEntry")
                        .HasColumnType("int");

                    b.Property<decimal>("SumApplied")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OdooErrorMsg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OdooLastSync")
                        .HasColumnType("datetime2");

                    b.Property<string>("OdooPaymentId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OdooStatus")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("OdooSyncDir")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("SapDocNum")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SapDocEntry");

                    b.HasIndex("InvoiceDocEntry");

                    b.HasIndex("OdooPaymentId");

                    b.HasIndex("OdooStatus");

                    b.ToTable("CachePayment", (string)null);
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Cache.CacheProduct", b =>
                {
                    b.Property<string>("ItemCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("WarehouseCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("AvailableCache")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Barcode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastSapSyncAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OdooErrorMsg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OdooLastSync")
                        .HasColumnType("datetime2");

                    b.Property<string>("OdooPricelistId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OdooProductId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OdooStatus")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("OdooSyncDir")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("OnHandSap")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("PriceList_1")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PriceList_2")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PriceList_3")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("ItemCode", "WarehouseCode");

                    b.HasIndex("Barcode");

                    b.HasIndex("ItemCode");

                    b.HasIndex("OdooProductId");

                    b.HasIndex("OdooStatus");

                    b.HasIndex("WarehouseCode");

                    b.ToTable("CacheProducts", (string)null);
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Cache.CacheSalesOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CancelReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("DocDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocStatus")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<decimal>("DocTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OdooErrorMsg")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("OdooLastSync")
                        .HasColumnType("datetime2");

                    b.Property<string>("OdooSalesOrderId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OdooStatus")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("OdooSyncDir")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("SapDocEntry")
                        .HasColumnType("int");

                    b.Property<int>("SapDocNum")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OdooSalesOrderId");

                    b.HasIndex("OdooStatus");

                    b.HasIndex("SapDocEntry")
                        .IsUnique();

                    b.ToTable("CacheSalesOrders", (string)null);
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Cache.CacheSalesOrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ItemName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LineNum")
                        .HasColumnType("int");

                    b.Property<string>("OdooSalesOrderLineId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("SapDocEntry")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OdooSalesOrderLineId");

                    b.HasIndex("SapDocEntry");

                    b.ToTable("CacheSalesOrderLines", (string)null);
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Cache.CacheStockReservation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCommitted")
                        .HasColumnType("bit");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OdooSalesOrderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Reference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SapDocEntry")
                        .HasColumnType("int");

                    b.Property<string>("WarehouseCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ItemCode", "WarehouseCode");

                    b.ToTable("CacheStockReservations", (string)null);
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Cache.CacheDeliveryLine", b =>
                {
                    b.HasOne("MolasLubes.Domain.Entities.Cache.CacheDelivery", "Delivery")
                        .WithMany("Lines")
                        .HasForeignKey("SapDocEntry")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Delivery");
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Cache.CacheInvoiceLine", b =>
                {
                    b.HasOne("MolasLubes.Domain.Entities.Cache.CacheInvoice", "Invoice")
                        .WithMany("Lines")
                        .HasForeignKey("SapDocEntry")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Cache.CacheSalesOrderLine", b =>
                {
                    b.HasOne("MolasLubes.Domain.Entities.Cache.CacheSalesOrder", "SalesOrder")
                        .WithMany("Lines")
                        .HasForeignKey("SapDocEntry")
                        .HasPrincipalKey("SapDocEntry")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SalesOrder");
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Cache.CacheDelivery", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Cache.CacheInvoice", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Cache.CacheSalesOrder", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
