// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MolasLubes.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MolasLubes.Infrastructure.Persistence.Migrations.AutoHub
{
    [DbContext(typeof(AutoHubDbContext))]
    [Migration("20260701000002_AddAutoHubSalesPersonTable")]
    partial class AddAutoHubSalesPersonTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // ── NeonGermaxProduct ────────────────────────────────────────────
            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonGermaxProduct", b =>
                {
                    b.Property<string>("ItemCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("item_code");

                    b.Property<string>("AllImageUrls")
                        .HasColumnType("text")
                        .HasColumnName("all_image_urls");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EngineCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("engine_code");

                    b.Property<string>("FitForAuto")
                        .HasColumnType("text")
                        .HasColumnName("fit_for_auto");

                    b.Property<string>("GermaxArticleNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("germax_article_number");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("ItemGroupName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("item_group_name");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_name");

                    b.Property<DateTime>("LastSapSeedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sap_seed_at");

                    b.Property<string>("MatchMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("match_method");

                    b.Property<decimal?>("MatchScore")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("match_score");

                    b.Property<string>("OemPartNumber")
                        .HasColumnType("text")
                        .HasColumnName("oem_part_number");

                    b.Property<string>("ProductUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("product_url");

                    b.Property<string>("ScrapeError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("scrape_error");

                    b.Property<string>("ScrapeStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("scrape_status");

                    b.Property<DateTime?>("ScrapedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scraped_at");

                    b.HasKey("ItemCode");

                    b.HasIndex("EngineCode")
                        .HasDatabaseName("ix_neon_germax_products_engine_code");

                    b.HasIndex("GermaxArticleNumber")
                        .HasDatabaseName("ix_neon_germax_products_germax_article_number");

                    b.HasIndex("ItemGroupName")
                        .HasDatabaseName("ix_neon_germax_products_item_group_name");

                    b.HasIndex("ScrapedAt")
                        .HasDatabaseName("ix_neon_germax_products_scraped_at");

                    b.ToTable("neon_germax_products", (string)null);
                });

            // ── NeonAutoHubProduct ───────────────────────────────────────────
            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonAutoHubProduct", b =>
                {
                    b.Property<string>("ItemCode")
                        .HasColumnType("text");

                    b.Property<decimal>("AvailableCache")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("OnHandSap")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("U_Article_No")
                        .HasColumnType("text");

                    b.Property<string>("U_Item_Name")
                        .HasColumnType("text");

                    b.Property<string>("U_MdlTEST")
                        .HasColumnType("text");

                    b.Property<string>("U_OriginalNumber")
                        .HasColumnType("text");

                    b.Property<string>("U_PT_No_Inproduction")
                        .HasColumnType("text");

                    b.Property<string>("U_ReferenceNum")
                        .HasColumnType("text");

                    b.HasKey("ItemCode");

                    b.ToTable("NeonAutoHubProducts", (string)null);
                });

            // ── NeonAutoHubSyncState ─────────────────────────────────────────
            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonAutoHubSyncState", b =>
                {
                    b.Property<string>("DocType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DocType");

                    b.ToTable("NeonAutoHubSyncState", (string)null);
                });

            // ── NeonAutoHubDelivery ──────────────────────────────────────────
            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonAutoHubDelivery", b =>
                {
                    b.Property<int>("DocEntry")
                        .ValueGeneratedNever()
                        .HasColumnType("integer");

                    b.Property<string>("CardCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CardName")
                        .HasColumnType("text");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<DateTime>("DocDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DocNum")
                        .HasColumnType("integer");

                    b.Property<string>("DocStatus")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedInSap")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DocEntry");

                    b.HasIndex("CardCode");

                    b.HasIndex("DocDate");

                    b.ToTable("NeonAutoHubDeliveries", (string)null);
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonAutoHubDeliveryLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DocEntry")
                        .HasColumnType("integer");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LineNum")
                        .HasColumnType("integer");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("WhsCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DocEntry");

                    b.HasIndex("ItemCode");

                    b.ToTable("NeonAutoHubDeliveryLines", (string)null);
                });

            // ── NeonAutoHubSalesOrder ────────────────────────────────────────
            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonAutoHubSalesOrder", b =>
                {
                    b.Property<int>("DocEntry")
                        .ValueGeneratedNever()
                        .HasColumnType("integer");

                    b.Property<string>("CardCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CardName")
                        .HasColumnType("text");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<DateTime>("DocDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DocDueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DocNum")
                        .HasColumnType("integer");

                    b.Property<string>("DocStatus")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<decimal>("DocTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedInSap")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DocEntry");

                    b.HasIndex("DocDate");

                    b.HasIndex("DocStatus");

                    b.ToTable("NeonAutoHubSalesOrders", (string)null);
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonAutoHubSalesOrderLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DocEntry")
                        .HasColumnType("integer");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LineNum")
                        .HasColumnType("integer");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("OpenQty")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("WhsCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DocEntry");

                    b.HasIndex("ItemCode");

                    b.ToTable("NeonAutoHubSalesOrderLines", (string)null);
                });

            // ── NeonAutoHubInvoice ───────────────────────────────────────────
            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonAutoHubInvoice", b =>
                {
                    b.Property<int>("DocEntry")
                        .ValueGeneratedNever()
                        .HasColumnType("integer");

                    b.Property<string>("CardCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CardName")
                        .HasColumnType("text");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<DateTime>("DocDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DocNum")
                        .HasColumnType("integer");

                    b.Property<string>("DocStatus")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<decimal>("DocTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PaidToDate")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedInSap")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("VatSum")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("DocEntry");

                    b.HasIndex("DocDate");

                    b.ToTable("NeonAutoHubInvoices", (string)null);
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonAutoHubInvoiceLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DocEntry")
                        .HasColumnType("integer");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LineNum")
                        .HasColumnType("integer");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("WhsCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DocEntry");

                    b.HasIndex("ItemCode");

                    b.ToTable("NeonAutoHubInvoiceLines", (string)null);
                });

            // ── NeonAutoHubGoodsReceipt ──────────────────────────────────────
            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonAutoHubGoodsReceipt", b =>
                {
                    b.Property<int>("DocEntry")
                        .ValueGeneratedNever()
                        .HasColumnType("integer");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<DateTime>("DocDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DocNum")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedInSap")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DocEntry");

                    b.HasIndex("DocDate");

                    b.ToTable("NeonAutoHubGoodsReceipts", (string)null);
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonAutoHubGoodsReceiptLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DocEntry")
                        .HasColumnType("integer");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LineNum")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("WhsCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DocEntry");

                    b.HasIndex("ItemCode");

                    b.ToTable("NeonAutoHubGoodsReceiptLines", (string)null);
                });

            // ── NeonAutoHubStockTransfer ─────────────────────────────────────
            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonAutoHubStockTransfer", b =>
                {
                    b.Property<int>("DocEntry")
                        .ValueGeneratedNever()
                        .HasColumnType("integer");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<DateTime>("DocDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DocNum")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedInSap")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DocEntry");

                    b.HasIndex("DocDate");

                    b.ToTable("NeonAutoHubStockTransfers", (string)null);
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonAutoHubStockTransferLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DocEntry")
                        .HasColumnType("integer");

                    b.Property<string>("FromWhsCode")
                        .HasColumnType("text");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LineNum")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("ToWhsCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DocEntry");

                    b.HasIndex("ItemCode");

                    b.ToTable("NeonAutoHubStockTransferLines", (string)null);
                });

            // ── NeonAutoHubInventoryCounting ─────────────────────────────────
            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonAutoHubInventoryCounting", b =>
                {
                    b.Property<int>("DocEntry")
                        .ValueGeneratedNever()
                        .HasColumnType("integer");

                    b.Property<DateTime>("CountDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DocNum")
                        .HasColumnType("integer");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedInSap")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DocEntry");

                    b.HasIndex("CountDate");

                    b.ToTable("NeonAutoHubInventoryCountings", (string)null);
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonAutoHubInventoryCountingLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("CountedQty")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("DocEntry")
                        .HasColumnType("integer");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LineNum")
                        .HasColumnType("integer");

                    b.Property<string>("WhsCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DocEntry");

                    b.HasIndex("ItemCode");

                    b.ToTable("NeonAutoHubInventoryCountingLines", (string)null);
                });

            // ── NeonAutoHubPurchaseOrder ─────────────────────────────────────
            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonAutoHubPurchaseOrder", b =>
                {
                    b.Property<int>("DocEntry")
                        .ValueGeneratedNever()
                        .HasColumnType("integer");

                    b.Property<string>("CardCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CardName")
                        .HasColumnType("text");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<DateTime>("DocDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DocDueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DocNum")
                        .HasColumnType("integer");

                    b.Property<string>("DocStatus")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<decimal>("DocTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedInSap")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DocEntry");

                    b.HasIndex("DocDate");

                    b.HasIndex("DocStatus");

                    b.ToTable("NeonAutoHubPurchaseOrders", (string)null);
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonAutoHubPurchaseOrderLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DocEntry")
                        .HasColumnType("integer");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LineNum")
                        .HasColumnType("integer");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("OpenQty")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("WhsCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DocEntry");

                    b.HasIndex("ItemCode");

                    b.ToTable("NeonAutoHubPurchaseOrderLines", (string)null);
                });

            // ── NeonAutoHubUoM ───────────────────────────────────────────────
            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonAutoHubUoM", b =>
                {
                    b.Property<int>("UomEntry")
                        .ValueGeneratedNever()
                        .HasColumnType("integer");

                    b.Property<int?>("GroupEntry")
                        .HasColumnType("integer");

                    b.Property<string>("UomCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("UomName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("UomEntry");

                    b.ToTable("NeonAutoHubUoMs", (string)null);
                });

            // ── NeonAutoHubSalesPerson ───────────────────────────────────────
            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonAutoHubSalesPerson", b =>
                {
                    b.Property<int>("SalesPersonCode")
                        .ValueGeneratedNever()
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("SalesPersonName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SalesPersonCode");

                    b.ToTable("NeonAutoHubSalesPersons", (string)null);
                });

            // ── Relationships ────────────────────────────────────────────────

            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonAutoHubDeliveryLine", b =>
                {
                    b.HasOne("MolasLubes.Domain.Entities.Neon.NeonAutoHubDelivery", "Delivery")
                        .WithMany("Lines")
                        .HasForeignKey("DocEntry")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Delivery");
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonAutoHubGoodsReceiptLine", b =>
                {
                    b.HasOne("MolasLubes.Domain.Entities.Neon.NeonAutoHubGoodsReceipt", "GoodsReceipt")
                        .WithMany("Lines")
                        .HasForeignKey("DocEntry")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoodsReceipt");
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonAutoHubInventoryCountingLine", b =>
                {
                    b.HasOne("MolasLubes.Domain.Entities.Neon.NeonAutoHubInventoryCounting", "InventoryCounting")
                        .WithMany("Lines")
                        .HasForeignKey("DocEntry")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryCounting");
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonAutoHubInvoiceLine", b =>
                {
                    b.HasOne("MolasLubes.Domain.Entities.Neon.NeonAutoHubInvoice", "Invoice")
                        .WithMany("Lines")
                        .HasForeignKey("DocEntry")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonAutoHubPurchaseOrderLine", b =>
                {
                    b.HasOne("MolasLubes.Domain.Entities.Neon.NeonAutoHubPurchaseOrder", "PurchaseOrder")
                        .WithMany("Lines")
                        .HasForeignKey("DocEntry")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonAutoHubSalesOrderLine", b =>
                {
                    b.HasOne("MolasLubes.Domain.Entities.Neon.NeonAutoHubSalesOrder", "SalesOrder")
                        .WithMany("Lines")
                        .HasForeignKey("DocEntry")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SalesOrder");
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonAutoHubStockTransferLine", b =>
                {
                    b.HasOne("MolasLubes.Domain.Entities.Neon.NeonAutoHubStockTransfer", "StockTransfer")
                        .WithMany("Lines")
                        .HasForeignKey("DocEntry")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StockTransfer");
                });

            // ── Navigation back-references ───────────────────────────────────

            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonAutoHubDelivery", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonAutoHubGoodsReceipt", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonAutoHubInventoryCounting", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonAutoHubInvoice", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonAutoHubPurchaseOrder", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonAutoHubSalesOrder", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonAutoHubStockTransfer", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
