// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MolasLubes.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MolasLubes.Infrastructure.Persistence.Migrations.AutoHub
{
    [DbContext(typeof(AutoHubDbContext))]
    partial class AutoHubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonGermaxProduct", b =>
                {
                    b.Property<string>("ItemCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("item_code");

                    b.Property<string>("AllImageUrls")
                        .HasColumnType("text")
                        .HasColumnName("all_image_urls");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EngineCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("engine_code");

                    b.Property<string>("FitForAuto")
                        .HasColumnType("text")
                        .HasColumnName("fit_for_auto");

                    b.Property<string>("GermaxArticleNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("germax_article_number");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("ItemGroupName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("item_group_name");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_name");

                    b.Property<DateTime>("LastSapSeedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sap_seed_at");

                    b.Property<string>("MatchMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("match_method");

                    b.Property<decimal?>("MatchScore")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("match_score");

                    b.Property<string>("OemPartNumber")
                        .HasColumnType("text")
                        .HasColumnName("oem_part_number");

                    b.Property<string>("PartsCatalog")
                        .HasColumnType("text")
                        .HasColumnName("parts_catalog");

                    b.Property<string>("ProductUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("product_url");

                    b.Property<string>("ScrapeError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("scrape_error");

                    b.Property<string>("ScrapeStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("scrape_status");

                    b.Property<DateTime?>("ScrapedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scraped_at");

                    b.HasKey("ItemCode");

                    b.HasIndex("EngineCode")
                        .HasDatabaseName("ix_neon_germax_products_engine_code");

                    b.HasIndex("GermaxArticleNumber")
                        .HasDatabaseName("ix_neon_germax_products_germax_article_number");

                    b.HasIndex("ItemGroupName")
                        .HasDatabaseName("ix_neon_germax_products_item_group_name");

                    b.HasIndex("ScrapedAt")
                        .HasDatabaseName("ix_neon_germax_products_scraped_at");

                    b.ToTable("neon_germax_products", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
