// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MolasLubes.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MolasLubes.Infrastructure.Persistence.Migrations.AutoHub
{
    [DbContext(typeof(AutoHubDbContext))]
    partial class AutoHubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonGermaxProduct", b =>
                {
                    b.Property<string>("ItemCode")
                        .HasMaxLength(50)
                        .HasColumnName("item_code")
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnName("item_name")
                        .HasColumnType("text");

                    b.Property<string>("ItemGroupName")
                        .HasMaxLength(100)
                        .HasColumnName("item_group_name")
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EngineCode")
                        .HasMaxLength(100)
                        .HasColumnName("engine_code")
                        .HasColumnType("character varying(100)");

                    b.Property<string>("GermaxArticleNumber")
                        .HasMaxLength(50)
                        .HasColumnName("germax_article_number")
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OemPartNumber")
                        .HasColumnName("oem_part_number")
                        .HasColumnType("text");

                    b.Property<string>("FitForAuto")
                        .HasColumnName("fit_for_auto")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnName("description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnName("image_url")
                        .HasColumnType("character varying(500)");

                    b.Property<string>("AllImageUrls")
                        .HasColumnName("all_image_urls")
                        .HasColumnType("text");

                    b.Property<string>("ProductUrl")
                        .HasMaxLength(500)
                        .HasColumnName("product_url")
                        .HasColumnType("character varying(500)");

                    b.Property<string>("MatchMethod")
                        .HasMaxLength(50)
                        .HasColumnName("match_method")
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("MatchScore")
                        .HasColumnName("match_score")
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime?>("ScrapedAt")
                        .HasColumnName("scraped_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSapSeedAt")
                        .HasColumnName("last_sap_seed_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active")
                        .HasColumnType("boolean");

                    b.Property<string>("ScrapeStatus")
                        .HasMaxLength(20)
                        .HasColumnName("scrape_status")
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ScrapeError")
                        .HasMaxLength(1000)
                        .HasColumnName("scrape_error")
                        .HasColumnType("character varying(1000)");

                    b.HasKey("ItemCode")
                        .HasName("pk_neon_germax_products");

                    b.HasIndex("GermaxArticleNumber")
                        .HasDatabaseName("ix_neon_germax_products_germax_article_number");

                    b.HasIndex("ItemGroupName")
                        .HasDatabaseName("ix_neon_germax_products_item_group_name");

                    b.HasIndex("EngineCode")
                        .HasDatabaseName("ix_neon_germax_products_engine_code");

                    b.HasIndex("ScrapedAt")
                        .HasDatabaseName("ix_neon_germax_products_scraped_at");

                    b.ToTable("neon_germax_products", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
