// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MolasLubes.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MolasLubes.Infrastructure.Persistence.Migrations.Neon
{
    [DbContext(typeof(NeonDbContext))]
    [Migration("20260701000003_AddAutoHubDocumentTables")]
    partial class AddAutoHubDocumentTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonApiCache", b =>
                {
                    b.Property<string>("CacheKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("CachedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CacheKey");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("NeonApiCache", (string)null);
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonCustomer", b =>
                {
                    b.Property<string>("CardCode")
                        .HasColumnType("text");

                    b.Property<decimal>("AvailableCredit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("BillToCity")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BillToCountry")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("BillToStreet")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("CreditLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("OdooErrorMsg")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("OdooLastSync")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OdooPartnerId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("OdooStatus")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("OdooSyncDir")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("OutstandingBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Phone1")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Phone2")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("PriceList")
                        .HasColumnType("integer");

                    b.Property<int?>("SalesPersonCode")
                        .HasColumnType("integer");

                    b.Property<string>("SalesPersonName")
                        .HasColumnType("text");

                    b.Property<string>("ShipToCity")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ShipToCountry")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ShipToStreet")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CardCode");

                    b.ToTable("NeonCustomers", (string)null);
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonDelivery", b =>
                {
                    b.Property<int>("SapDocEntry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SapDocEntry"));

                    b.Property<int?>("BaseOrderEntry")
                        .HasColumnType("integer");

                    b.Property<string>("CardCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("DeliveredQty")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean");

                    b.Property<string>("OdooDeliveryId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("OdooErrorMsg")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("OdooLastSync")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OdooStatus")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("OdooSyncDir")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("SalesOrderEntry")
                        .HasColumnType("integer");

                    b.Property<int>("SapDocNum")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SapDocEntry");

                    b.ToTable("NeonDeliveries", (string)null);
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonDeliveryLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("BaseEntry")
                        .HasColumnType("integer");

                    b.Property<int>("BaseLine")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("DeliveryEntry")
                        .HasColumnType("integer");

                    b.Property<decimal>("GrossBuyPr")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("LineNum")
                        .HasColumnType("integer");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("OdooErrorMsg")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("OdooLastSync")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OdooMoveId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("OdooSalesOrderLineId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("OdooStatus")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("OdooSyncDir")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryEntry");

                    b.HasIndex("OdooMoveId");

                    b.ToTable("NeonDeliveryLines", (string)null);
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonInvoice", b =>
                {
                    b.Property<int>("SapDocEntry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SapDocEntry"));

                    b.Property<string>("CardName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DocNum")
                        .HasColumnType("integer");

                    b.Property<decimal>("DocTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("VatSum")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<string>("OdooErrorMsg")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("OdooInvoiceId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("OdooLastSync")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OdooStatus")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("OdooSyncDir")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("PaidAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SapDocEntry");

                    b.HasIndex("SyncedAt");

                    b.ToTable("NeonInvoices", (string)null);
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonInvoiceLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("BaseEntry")
                        .HasColumnType("integer");

                    b.Property<int>("BaseLine")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("GrossBuyPr")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("InvoiceEntry")
                        .HasColumnType("integer");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("OdooErrorMsg")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("OdooInvoiceLineId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("OdooLastSync")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OdooStatus")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("OdooSyncDir")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceEntry");

                    b.HasIndex("OdooInvoiceLineId");

                    b.ToTable("NeonInvoiceLines", (string)null);
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonLiquiMolyProduct", b =>
                {
                    b.Property<string>("ArticleNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("AllImageUrls")
                        .HasColumnType("text");

                    b.Property<string>("AllPackagingSizes")
                        .HasColumnType("text");

                    b.Property<string>("AllBarcodes")
                        .HasColumnType("text");

                    b.Property<string>("Approvals")
                        .HasColumnType("text");

                    b.Property<string>("Application")
                        .HasColumnType("text");

                    b.Property<string>("BarcodeResolutionNote")
                        .HasColumnType("text");

                    b.Property<string>("EanCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("BarcodeResolutionStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasUnitBarcode")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PackagingSize")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal?>("Liter")
                        .HasColumnType("numeric(8,3)");

                    b.Property<string>("OverviewProperties")
                        .HasColumnType("text");

                    b.Property<string>("LiquiMolyRecommendations")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryBarcode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("PrimaryBarcodeBaseQtyInGroup")
                        .HasColumnType("numeric(19,6)");

                    b.Property<int?>("PrimaryBarcodeUomEntry")
                        .HasColumnType("integer");

                    b.Property<string>("PrimaryBarcodeUomCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PrimaryBarcodeUomName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProductInfoPdfUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ProductUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SafetyDataSheetPdfUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SapUomInfo")
                        .HasColumnType("text");

                    b.Property<DateTime>("ScrapedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Specifications")
                        .HasColumnType("text");

                    b.Property<string>("SpecificationItems")
                        .HasColumnType("text");

                    b.Property<string>("SpecGrade")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SubCategory")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ArticleNumber");

                    b.HasIndex("Category");

                    b.HasIndex("IsActive");

                    b.HasIndex("ScrapedAt");

                    b.ToTable("NeonLiquiMolyProducts", (string)null);
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonPayment", b =>
                {
                    b.Property<int>("SapDocEntry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SapDocEntry"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DocNum")
                        .HasColumnType("integer");

                    b.Property<int>("InvoiceEntry")
                        .HasColumnType("integer");

                    b.Property<string>("OdooErrorMsg")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("OdooLastSync")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OdooPaymentId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("OdooStatus")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("OdooSyncDir")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SapDocEntry");

                    b.HasIndex("InvoiceEntry");

                    b.ToTable("NeonPayments", (string)null);
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonPriceList", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OdooErrorMsg")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("OdooLastSync")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OdooPricelistId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("OdooStatus")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("OdooSyncDir")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("PriceList")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ItemCode", "PriceList")
                        .IsUnique();

                    b.ToTable("NeonPriceLists", (string)null);
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonProduct", b =>
                {
                    b.Property<string>("ItemCode")
                        .HasColumnType("text");

                    b.Property<decimal>("AvailableCache")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Barcode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<string>("DefaultWarehouse")
                        .HasColumnType("text");

                    b.Property<string>("ForeignName")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsInventoryItem")
                        .HasColumnType("boolean");

                    b.Property<int?>("ItemGroupCode")
                        .HasColumnType("integer");

                    b.Property<string>("ItemGroupName")
                        .HasColumnType("text");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OdooErrorMsg")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("OdooLastSync")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OdooProductId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("OdooStatus")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("OdooSyncDir")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("OnHandSap")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UoM")
                        .HasColumnType("text");

                    b.HasKey("ItemCode");

                    b.HasIndex("Barcode");

                    b.HasIndex("Brand");

                    b.ToTable("NeonProducts", (string)null);
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonSalesOrder", b =>
                {
                    b.Property<int>("SapDocEntry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SapDocEntry"));

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DocDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DocNum")
                        .HasColumnType("integer");

                    b.Property<decimal>("DocTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("OdooErrorMsg")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("OdooLastSync")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OdooSalesOrderId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("OdooStatus")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("OdooSyncDir")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int?>("SalesPersonCode")
                        .HasColumnType("integer");

                    b.Property<string>("SalesPersonName")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SapDocEntry");

                    b.ToTable("NeonSalesOrders", (string)null);
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonSalesOrderLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("OdooSalesOrderLineId")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("SalesOrderEntry")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OdooSalesOrderLineId");

                    b.HasIndex("SalesOrderEntry");

                    b.ToTable("NeonSalesOrderLines", (string)null);
                });

            // ── Relationships ─────────────────────────────────────────────────

            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonDeliveryLine", b =>
                {
                    b.HasOne("MolasLubes.Domain.Entities.Neon.NeonDelivery", "Delivery")
                        .WithMany("Lines")
                        .HasForeignKey("DeliveryEntry")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Delivery");
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonInvoiceLine", b =>
                {
                    b.HasOne("MolasLubes.Domain.Entities.Neon.NeonInvoice", "Invoice")
                        .WithMany("Lines")
                        .HasForeignKey("InvoiceEntry")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonPayment", b =>
                {
                    b.HasOne("MolasLubes.Domain.Entities.Neon.NeonInvoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceEntry")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonSalesOrderLine", b =>
                {
                    b.HasOne("MolasLubes.Domain.Entities.Neon.NeonSalesOrder", "SalesOrder")
                        .WithMany("Lines")
                        .HasForeignKey("SalesOrderEntry")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SalesOrder");
                });

            // ── Navigation back-references ────────────────────────────────────

            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonDelivery", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonInvoice", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonSalesOrder", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
