// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MolasLubes.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MolasLubes.Infrastructure.Persistence.Migrations.Neon
{
    [DbContext(typeof(NeonDbContext))]
    [Migration("20260210083457_InitialNeonSchema")]
    partial class InitialNeonSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonCustomer", b =>
                {
                    b.Property<string>("CardCode")
                        .HasColumnType("text");

                    b.Property<decimal>("AvailableCredit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("CreditLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("OdooErrorMsg")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("OdooLastSync")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OdooPartnerId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("OdooStatus")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("OdooSyncDir")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("OutstandingBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("SalesPersonCode")
                        .HasColumnType("integer");

                    b.Property<string>("SalesPersonName")
                        .HasColumnType("text");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CardCode");

                    b.ToTable("NeonCustomers", (string)null);
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonDelivery", b =>
                {
                    b.Property<int>("SapDocEntry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SapDocEntry"));

                    b.Property<int?>("BaseOrderEntry")
                        .HasColumnType("integer");

                    b.Property<string>("CardCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("DeliveredQty")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean");

                    b.Property<string>("OdooDeliveryId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("OdooErrorMsg")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("OdooLastSync")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OdooStatus")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("OdooSyncDir")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("SalesOrderEntry")
                        .HasColumnType("integer");

                    b.Property<int>("SapDocNum")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SapDocEntry");

                    b.ToTable("NeonDeliveries", (string)null);
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonInvoice", b =>
                {
                    b.Property<int>("SapDocEntry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SapDocEntry"));

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DocNum")
                        .HasColumnType("integer");

                    b.Property<decimal>("DocTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<string>("OdooErrorMsg")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("OdooInvoiceId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("OdooLastSync")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OdooStatus")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("OdooSyncDir")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("PaidAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SapDocEntry");

                    b.ToTable("NeonInvoices", (string)null);
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonPayment", b =>
                {
                    b.Property<int>("SapDocEntry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SapDocEntry"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DocNum")
                        .HasColumnType("integer");

                    b.Property<string>("OdooErrorMsg")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("OdooLastSync")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OdooPaymentId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("OdooStatus")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("OdooSyncDir")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SapDocEntry");

                    b.ToTable("NeonPayments", (string)null);
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonPriceList", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OdooErrorMsg")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("OdooLastSync")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OdooPricelistId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("OdooStatus")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("OdooSyncDir")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("PriceList")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ItemCode", "PriceList")
                        .IsUnique();

                    b.ToTable("NeonPriceLists", (string)null);
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonProduct", b =>
                {
                    b.Property<string>("ItemCode")
                        .HasColumnType("text");

                    b.Property<decimal>("AvailableCache")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<string>("DefaultWarehouse")
                        .HasColumnType("text");

                    b.Property<string>("ForeignName")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsInventoryItem")
                        .HasColumnType("boolean");

                    b.Property<int?>("ItemGroupCode")
                        .HasColumnType("integer");

                    b.Property<string>("ItemGroupName")
                        .HasColumnType("text");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OdooErrorMsg")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("OdooLastSync")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OdooProductId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("OdooStatus")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("OdooSyncDir")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("OnHandSap")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UoM")
                        .HasColumnType("text");

                    b.HasKey("ItemCode");

                    b.ToTable("NeonProducts", (string)null);
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonSalesOrder", b =>
                {
                    b.Property<int>("SapDocEntry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SapDocEntry"));

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DocDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DocNum")
                        .HasColumnType("integer");

                    b.Property<decimal>("DocTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("OdooErrorMsg")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("OdooLastSync")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OdooSalesOrderId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("OdooStatus")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("OdooSyncDir")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int?>("SalesPersonCode")
                        .HasColumnType("integer");

                    b.Property<string>("SalesPersonName")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SapDocEntry");

                    b.ToTable("NeonSalesOrders", (string)null);
                });

            modelBuilder.Entity("MolasLubes.Domain.Entities.Neon.NeonSalesOrderLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("OdooSalesOrderLineId")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("SalesOrderEntry")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("NeonSalesOrderLines", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
