include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**/*.freezed.dart'
    - '**/*.g.dart'
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    - always_declare_return_types
    - always_use_package_imports
    - avoid_empty_else
    - avoid_print
    - avoid_unnecessary_containers
    - cancel_subscriptions
    - close_sinks
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_locals
    - prefer_relative_imports
    - sort_child_properties_last
    - unawaited_futures
    - unnecessary_await_in_return
    - use_key_in_widget_constructors
